/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WelcomeImport } from './routes/welcome'
import { Route as DashboardViewsImport } from './routes/dashboard-views'
import { Route as DashboardHomeImport } from './routes/dashboard-home'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WelcomeRoute = WelcomeImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRoute,
} as any)

const DashboardViewsRoute = DashboardViewsImport.update({
  id: '/dashboard-views',
  path: '/dashboard-views',
  getParentRoute: () => rootRoute,
} as any)

const DashboardHomeRoute = DashboardHomeImport.update({
  id: '/dashboard-home',
  path: '/dashboard-home',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/dashboard-home': {
      id: '/dashboard-home'
      path: '/dashboard-home'
      fullPath: '/dashboard-home'
      preLoaderRoute: typeof DashboardHomeImport
      parentRoute: typeof rootRoute
    }
    '/dashboard-views': {
      id: '/dashboard-views'
      path: '/dashboard-views'
      fullPath: '/dashboard-views'
      preLoaderRoute: typeof DashboardViewsImport
      parentRoute: typeof rootRoute
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard-home': typeof DashboardHomeRoute
  '/dashboard-views': typeof DashboardViewsRoute
  '/welcome': typeof WelcomeRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard-home': typeof DashboardHomeRoute
  '/dashboard-views': typeof DashboardViewsRoute
  '/welcome': typeof WelcomeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard-home': typeof DashboardHomeRoute
  '/dashboard-views': typeof DashboardViewsRoute
  '/welcome': typeof WelcomeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard-home'
    | '/dashboard-views'
    | '/welcome'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/dashboard-home' | '/dashboard-views' | '/welcome'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard-home'
    | '/dashboard-views'
    | '/welcome'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardViewsRoute: typeof DashboardViewsRoute
  WelcomeRoute: typeof WelcomeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardViewsRoute: DashboardViewsRoute,
  WelcomeRoute: WelcomeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/dashboard-home",
        "/dashboard-views",
        "/welcome"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/dashboard-home": {
      "filePath": "dashboard-home.tsx"
    },
    "/dashboard-views": {
      "filePath": "dashboard-views.tsx"
    },
    "/welcome": {
      "filePath": "welcome.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
